# Generated by Django 3.0 on 2020-07-31 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('begin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoUpload',
        ),
    ]
