# Generated by Django 3.0 on 2020-07-31 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('begin', '0003_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='timestamp',
        ),
    ]
