# Generated by Django 4.2.2 on 2023-07-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='price',
            field=models.IntegerField(max_length=50),
        ),
    ]
